import '@/features/popup/popup'
import '@/features/fancybox'
import '@/features/fancybox'
import '@/features/forms'
import '@/features/check-fill'
import '@/features/inputMask'

import '@/ui/popups/cart/cart'
import '@/ui/product-item/product-item'
import '@/ui/selector/selector'
import '@/ui/size-table/size-table'
import '@/ui/tab-item/tab-item'
import '@/ui/cards/product-card'
import '@/ui/tabs-block/tabs-block'
import '@/ui/video-block/video-block'
import '@/ui/popups/shops-popup/shops-popup'
import '@/ui/rounded-input/rounded-input'
import '@/ui/popups/authorization/authorization'
import '@/ui/popups/search/search-popup'
import '@/ui/content/content.js'
import '@/ui/content-toc/content-toc'
import '@/ui/cookie/cookie'
import '@/ui/geo-notification/geo-notification'

import '@/ui/slider/slider'
import '@/ui/input/input.js'

import '@/pages/shops/shops'
import '@/pages/brands/brands'
import '@/pages/about/about'
