import '@/features/popup/popup'
import '@/features/fancybox'
import '@/features/fancybox'
import '@/features/forms'
import '@/features/check-fill'

import '@/ui/popups/cart/cart'
import '@/ui/product-item/product-item'
import '@/ui/selector/selector'
import '@/ui/size-table/size-table'
import '@/ui/tab-item/tab-item'
import '@/ui/cards/product-card'

import '@/ui/slider/slider'
import '@/ui/input/input.js'
